
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        config
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.config.php
* FOR MYSQL TABLE:  config
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class config
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $logomarca;   // (normal Attribute)
var $full_banner;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function config()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM config WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->logomarca = $row->logomarca;

$this->full_banner = $row->full_banner;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM config WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO config ( logomarca,full_banner ) VALUES ( '$this->logomarca','$this->full_banner' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE config SET  logomarca = '$this->logomarca',full_banner = '$this->full_banner' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
