
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        noticiasgeral
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.noticiasgeral.php
* FOR MYSQL TABLE:  noticiasgeral
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class noticiasgeral
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $titulo;   // (normal Attribute)
var $chamada;   // (normal Attribute)
var $imagem;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function noticiasgeral()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM noticiasgeral WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->titulo = $row->titulo;

$this->chamada = $row->chamada;

$this->imagem = $row->imagem;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM noticiasgeral WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO noticiasgeral ( titulo,chamada,imagem ) VALUES ( '$this->titulo','$this->chamada','$this->imagem' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE noticiasgeral SET  titulo = '$this->titulo',chamada = '$this->chamada',imagem = '$this->imagem' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
