<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        bairro
* GENERATION DATE:  21.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.bairro.php
* FOR MYSQL TABLE:  cad_bairro
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class bairro
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_uf;   // (normal Attribute)
var $idx_cid;   // (normal Attribute)
var $bai_nome;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function bairro()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_uf()
{
return $this->idx_uf;
}

function getidx_cid()
{
return $this->idx_cid;
}

function getbai_nome()
{
return $this->bai_nome;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_uf($val)
{
$this->idx_uf =  $val;
}

function setidx_cid($val)
{
$this->idx_cid =  $val;
}

function setbai_nome($val)
{
$this->bai_nome =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_bairro WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_uf = $row->idx_uf;

$this->idx_cid = $row->idx_cid;

$this->bai_nome = $row->bai_nome;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_bairro WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_bairro ( idx_uf,idx_cid,bai_nome ) VALUES ( '$this->idx_uf','$this->idx_cid','$this->bai_nome' )";
$result = $this->database->query($sql);
$this->id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_bairro SET  idx_uf = '$this->idx_uf',idx_cid = '$this->idx_cid',bai_nome = '$this->bai_nome' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>