
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        fornecedor
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.fornecedor.php
* FOR MYSQL TABLE:  cad_fornecedor
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class fornecedor
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_uf;   // (normal Attribute)
var $idx_cid;   // (normal Attribute)
var $idx_bai;   // (normal Attribute)
var $idx_lograd;   // (normal Attribute)
var $cep;   // (normal Attribute)
var $telefone;   // (normal Attribute)
var $e_mail;   // (normal Attribute)
var $fornec_nome;   // (normal Attribute)
var $cnpj;   // (normal Attribute)
var $numero;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function fornecedor()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_uf()
{
return $this->idx_uf;
}

function getidx_cid()
{
return $this->idx_cid;
}

function getidx_bai()
{
return $this->idx_bai;
}

function getidx_lograd()
{
return $this->idx_lograd;
}

function getcep()
{
return $this->cep;
}

function gettelefone()
{
return $this->telefone;
}

function gete_mail()
{
return $this->e_mail;
}

function getfornec_nome()
{
return $this->fornec_nome;
}

function getcnpj()
{
return $this->cnpj;
}

function getnumero()
{
return $this->numero;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_uf($val)
{
$this->idx_uf =  $val;
}

function setidx_cid($val)
{
$this->idx_cid =  $val;
}

function setidx_bai($val)
{
$this->idx_bai =  $val;
}

function setidx_lograd($val)
{
$this->idx_lograd =  $val;
}

function setcep($val)
{
$this->cep =  $val;
}

function settelefone($val)
{
$this->telefone =  $val;
}

function sete_mail($val)
{
$this->e_mail =  $val;
}

function setfornec_nome($val)
{
$this->fornec_nome =  $val;
}

function setcnpj($val)
{
$this->cnpj =  $val;
}

function setnumero($val)
{
$this->numero =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_fornecedor WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_uf = $row->idx_uf;

$this->idx_cid = $row->idx_cid;

$this->idx_bai = $row->idx_bai;

$this->idx_lograd = $row->idx_lograd;

$this->cep = $row->cep;

$this->telefone = $row->telefone;

$this->e_mail = $row->e_mail;

$this->fornec_nome = $row->fornec_nome;

$this->cnpj = $row->cnpj;

$this->numero = $row->numero;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_fornecedor WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_fornecedor ( idx_uf,idx_cid,idx_bai,idx_lograd,cep,telefone,e_mail,fornec_nome,cnpj,numero ) VALUES ( '$this->idx_uf','$this->idx_cid','$this->idx_bai','$this->idx_lograd','$this->cep','$this->telefone','$this->e_mail','$this->fornec_nome','$this->cnpj','$this->numero' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_fornecedor SET  idx_uf = '$this->idx_uf',idx_cid = '$this->idx_cid',idx_bai = '$this->idx_bai',idx_lograd = '$this->idx_lograd',cep = '$this->cep',telefone = '$this->telefone',e_mail = '$this->e_mail',fornec_nome = '$this->fornec_nome',cnpj = '$this->cnpj',numero = '$this->numero' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
