
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        despac_retorn
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.despac_retorn.php
* FOR MYSQL TABLE:  cad_despac_retorn
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class despac_retorn
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $situac_veic_equipam;   // (normal Attribute)
var $idx_equipam_devolv;   // (normal Attribute)
var $idx_despac_sai;   // (normal Attribute)
var $obs;   // (normal Attribute)
var $data_hora_ret;   // (normal Attribute)
var $kilom_final;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function despac_retorn()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getsituac_veic_equipam()
{
return $this->situac_veic_equipam;
}

function getidx_equipam_devolv()
{
return $this->idx_equipam_devolv;
}

function getidx_despac_sai()
{
return $this->idx_despac_sai;
}

function getobs()
{
return $this->obs;
}

function getdata_hora_ret()
{
return $this->data_hora_ret;
}

function getkilom_final()
{
return $this->kilom_final;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setsituac_veic_equipam($val)
{
$this->situac_veic_equipam =  $val;
}

function setidx_equipam_devolv($val)
{
$this->idx_equipam_devolv =  $val;
}

function setidx_despac_sai($val)
{
$this->idx_despac_sai =  $val;
}

function setobs($val)
{
$this->obs =  $val;
}

function setdata_hora_ret($val)
{
$this->data_hora_ret =  $val;
}

function setkilom_final($val)
{
$this->kilom_final =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_despac_retorn WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->situac_veic_equipam = $row->situac_veic_equipam;

$this->idx_equipam_devolv = $row->idx_equipam_devolv;

$this->idx_despac_sai = $row->idx_despac_sai;

$this->obs = $row->obs;

$this->data_hora_ret = $row->data_hora_ret;

$this->kilom_final = $row->kilom_final;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_despac_retorn WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_despac_retorn ( situac_veic_equipam,idx_equipam_devolv,idx_despac_sai,obs,data_hora_ret,kilom_final ) VALUES ( '$this->situac_veic_equipam','$this->idx_equipam_devolv','$this->idx_despac_sai','$this->obs','$this->data_hora_ret','$this->kilom_final' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_despac_retorn SET  situac_veic_equipam = '$this->situac_veic_equipam',idx_equipam_devolv = '$this->idx_equipam_devolv',idx_despac_sai = '$this->idx_despac_sai',obs = '$this->obs',data_hora_ret = '$this->data_hora_ret',kilom_final = '$this->kilom_final' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
