
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        fecha_vistor
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.fecha_vistor.php
* FOR MYSQL TABLE:  cad_fecha_vistor
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class fecha_vistor
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_os;   // (normal Attribute)
var $idx_semaforo;   // (normal Attribute)
var $funcionamento;   // (normal Attribute)
var $lampada;   // (normal Attribute)
var $botoeira;   // (normal Attribute)
var $semiportico;   // (normal Attribute)
var $porta_foco;   // (normal Attribute)
var $placa_num;   // (normal Attribute)
var $lente;   // (normal Attribute)
var $cobre_foco;   // (normal Attribute)
var $fiacao;   // (normal Attribute)
var $cincronismo;   // (normal Attribute)
var $tempos;   // (normal Attribute)
var $visibilidade;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function fecha_vistor()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_os()
{
return $this->idx_os;
}

function getidx_semaforo()
{
return $this->idx_semaforo;
}

function getfuncionamento()
{
return $this->funcionamento;
}

function getlampada()
{
return $this->lampada;
}

function getbotoeira()
{
return $this->botoeira;
}

function getsemiportico()
{
return $this->semiportico;
}

function getporta_foco()
{
return $this->porta_foco;
}

function getplaca_num()
{
return $this->placa_num;
}

function getlente()
{
return $this->lente;
}

function getcobre_foco()
{
return $this->cobre_foco;
}

function getfiacao()
{
return $this->fiacao;
}

function getcincronismo()
{
return $this->cincronismo;
}

function gettempos()
{
return $this->tempos;
}

function getvisibilidade()
{
return $this->visibilidade;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_os($val)
{
$this->idx_os =  $val;
}

function setidx_semaforo($val)
{
$this->idx_semaforo =  $val;
}

function setfuncionamento($val)
{
$this->funcionamento =  $val;
}

function setlampada($val)
{
$this->lampada =  $val;
}

function setbotoeira($val)
{
$this->botoeira =  $val;
}

function setsemiportico($val)
{
$this->semiportico =  $val;
}

function setporta_foco($val)
{
$this->porta_foco =  $val;
}

function setplaca_num($val)
{
$this->placa_num =  $val;
}

function setlente($val)
{
$this->lente =  $val;
}

function setcobre_foco($val)
{
$this->cobre_foco =  $val;
}

function setfiacao($val)
{
$this->fiacao =  $val;
}

function setcincronismo($val)
{
$this->cincronismo =  $val;
}

function settempos($val)
{
$this->tempos =  $val;
}

function setvisibilidade($val)
{
$this->visibilidade =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_fecha_vistor WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_os = $row->idx_os;

$this->idx_semaforo = $row->idx_semaforo;

$this->funcionamento = $row->funcionamento;

$this->lampada = $row->lampada;

$this->botoeira = $row->botoeira;

$this->semiportico = $row->semiportico;

$this->porta_foco = $row->porta_foco;

$this->placa_num = $row->placa_num;

$this->lente = $row->lente;

$this->cobre_foco = $row->cobre_foco;

$this->fiacao = $row->fiacao;

$this->cincronismo = $row->cincronismo;

$this->tempos = $row->tempos;

$this->visibilidade = $row->visibilidade;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_fecha_vistor WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_fecha_vistor ( idx_os,idx_semaforo,funcionamento,lampada,botoeira,semiportico,porta_foco,placa_num,lente,cobre_foco,fiacao,cincronismo,tempos,visibilidade ) VALUES ( '$this->idx_os','$this->idx_semaforo','$this->funcionamento','$this->lampada','$this->botoeira','$this->semiportico','$this->porta_foco','$this->placa_num','$this->lente','$this->cobre_foco','$this->fiacao','$this->cincronismo','$this->tempos','$this->visibilidade' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_fecha_vistor SET  idx_os = '$this->idx_os',idx_semaforo = '$this->idx_semaforo',funcionamento = '$this->funcionamento',lampada = '$this->lampada',botoeira = '$this->botoeira',semiportico = '$this->semiportico',porta_foco = '$this->porta_foco',placa_num = '$this->placa_num',lente = '$this->lente',cobre_foco = '$this->cobre_foco',fiacao = '$this->fiacao',cincronismo = '$this->cincronismo',tempos = '$this->tempos',visibilidade = '$this->visibilidade' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
