
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        junta_acess
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.junta_acess.php
* FOR MYSQL TABLE:  cad_junta_acess
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class junta_acess
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_acess;   // (normal Attribute)
var $idx_aux_aces;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function junta_acess()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_acess()
{
return $this->idx_acess;
}

function getidx_aux_aces()
{
return $this->idx_aux_aces;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_acess($val)
{
$this->idx_acess =  $val;
}

function setidx_aux_aces($val)
{
$this->idx_aux_aces =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_junta_acess WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_acess = $row->idx_acess;

$this->idx_aux_aces = $row->idx_aux_aces;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_junta_acess WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_junta_acess ( idx_acess,idx_aux_aces ) VALUES ( '$this->idx_acess','$this->idx_aux_aces' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_junta_acess SET  idx_acess = '$this->idx_acess',idx_aux_aces = '$this->idx_aux_aces' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
