
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        fornec_mater
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.fornec_mater.php
* FOR MYSQL TABLE:  cad_fornec_mater
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class fornec_mater
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_fornecedor;   // (normal Attribute)
var $idx_material;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function fornec_mater()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_fornecedor()
{
return $this->idx_fornecedor;
}

function getidx_material()
{
return $this->idx_material;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_fornecedor($val)
{
$this->idx_fornecedor =  $val;
}

function setidx_material($val)
{
$this->idx_material =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_fornec_mater WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_fornecedor = $row->idx_fornecedor;

$this->idx_material = $row->idx_material;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_fornec_mater WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_fornec_mater ( idx_fornecedor,idx_material ) VALUES ( '$this->idx_fornecedor','$this->idx_material' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_fornec_mater SET  idx_fornecedor = '$this->idx_fornecedor',idx_material = '$this->idx_material' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
