
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        empresa_usua
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.empresa_usua.php
* FOR MYSQL TABLE:  cad_empresa_usua
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class empresa_usua
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $razao_social;   // (normal Attribute)
var $tel;   // (normal Attribute)
var $e_mail;   // (normal Attribute)
var $cnpj;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function empresa_usua()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getrazao_social()
{
return $this->razao_social;
}

function gettel()
{
return $this->tel;
}

function gete_mail()
{
return $this->e_mail;
}

function getcnpj()
{
return $this->cnpj;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setrazao_social($val)
{
$this->razao_social =  $val;
}

function settel($val)
{
$this->tel =  $val;
}

function sete_mail($val)
{
$this->e_mail =  $val;
}

function setcnpj($val)
{
$this->cnpj =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_empresa_usua WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->razao_social = $row->razao_social;

$this->tel = $row->tel;

$this->e_mail = $row->e_mail;

$this->cnpj = $row->cnpj;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_empresa_usua WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_empresa_usua ( razao_social,tel,e_mail,cnpj ) VALUES ( '$this->razao_social','$this->tel','$this->e_mail','$this->cnpj' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_empresa_usua SET  razao_social = '$this->razao_social',tel = '$this->tel',e_mail = '$this->e_mail',cnpj = '$this->cnpj' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
