
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        despac_sai
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.despac_sai.php
* FOR MYSQL TABLE:  cad_despac_sai
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class despac_sai
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $num_ordem;   // (normal Attribute)
var $idx_veiculo;   // (normal Attribute)
var $idx_equipe;   // (normal Attribute)
var $data_hora;   // (normal Attribute)
var $situac_veic_equipam;   // (normal Attribute)
var $idx_equipam_acess;   // (normal Attribute)
var $idx_resp_tecnic;   // (normal Attribute)
var $motorista;   // (normal Attribute)
var $status_atual;   // (normal Attribute)
var $kilom_inicial;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function despac_sai()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getnum_ordem()
{
return $this->num_ordem;
}

function getidx_veiculo()
{
return $this->idx_veiculo;
}

function getidx_equipe()
{
return $this->idx_equipe;
}

function getdata_hora()
{
return $this->data_hora;
}

function getsituac_veic_equipam()
{
return $this->situac_veic_equipam;
}

function getidx_equipam_acess()
{
return $this->idx_equipam_acess;
}

function getidx_resp_tecnic()
{
return $this->idx_resp_tecnic;
}

function getmotorista()
{
return $this->motorista;
}

function getstatus_atual()
{
return $this->status_atual;
}

function getkilom_inicial()
{
return $this->kilom_inicial;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setnum_ordem($val)
{
$this->num_ordem =  $val;
}

function setidx_veiculo($val)
{
$this->idx_veiculo =  $val;
}

function setidx_equipe($val)
{
$this->idx_equipe =  $val;
}

function setdata_hora($val)
{
$this->data_hora =  $val;
}

function setsituac_veic_equipam($val)
{
$this->situac_veic_equipam =  $val;
}

function setidx_equipam_acess($val)
{
$this->idx_equipam_acess =  $val;
}

function setidx_resp_tecnic($val)
{
$this->idx_resp_tecnic =  $val;
}

function setmotorista($val)
{
$this->motorista =  $val;
}

function setstatus_atual($val)
{
$this->status_atual =  $val;
}

function setkilom_inicial($val)
{
$this->kilom_inicial =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_despac_sai WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->num_ordem = $row->num_ordem;

$this->idx_veiculo = $row->idx_veiculo;

$this->idx_equipe = $row->idx_equipe;

$this->data_hora = $row->data_hora;

$this->situac_veic_equipam = $row->situac_veic_equipam;

$this->idx_equipam_acess = $row->idx_equipam_acess;

$this->idx_resp_tecnic = $row->idx_resp_tecnic;

$this->motorista = $row->motorista;

$this->status_atual = $row->status_atual;

$this->kilom_inicial = $row->kilom_inicial;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_despac_sai WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_despac_sai ( num_ordem,idx_veiculo,idx_equipe,data_hora,situac_veic_equipam,idx_equipam_acess,idx_resp_tecnic,motorista,status_atual,kilom_inicial ) VALUES ( '$this->num_ordem','$this->idx_veiculo','$this->idx_equipe','$this->data_hora','$this->situac_veic_equipam','$this->idx_equipam_acess','$this->idx_resp_tecnic','$this->motorista','$this->status_atual','$this->kilom_inicial' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_despac_sai SET  num_ordem = '$this->num_ordem',idx_veiculo = '$this->idx_veiculo',idx_equipe = '$this->idx_equipe',data_hora = '$this->data_hora',situac_veic_equipam = '$this->situac_veic_equipam',idx_equipam_acess = '$this->idx_equipam_acess',idx_resp_tecnic = '$this->idx_resp_tecnic',motorista = '$this->motorista',status_atual = '$this->status_atual',kilom_inicial = '$this->kilom_inicial' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
