
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        produto
* GENERATION DATE:  03.07.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.produto.php
* FOR MYSQL TABLE:  produto
* FOR MYSQL DB:     stockcontrol
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class produto
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $codigo;   // (normal Attribute)
var $nome;   // (normal Attribute)
var $quantidade;   // (normal Attribute)
var $quantidadeMinima;   // (normal Attribute)
var $valor;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function produto()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM produto WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->codigo = $row->codigo;

$this->nome = $row->nome;

$this->quantidade = $row->quantidade;

$this->quantidadeMinima = $row->quantidadeMinima;

$this->valor = $row->valor;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM produto WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO produto ( codigo,nome,quantidade,quantidadeMinima,valor ) VALUES ( '$this->codigo','$this->nome','$this->quantidade','$this->quantidadeMinima','$this->valor' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE produto SET  codigo = '$this->codigo',nome = '$this->nome',quantidade = '$this->quantidade',quantidadeMinima = '$this->quantidadeMinima',valor = '$this->valor' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
