
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        pedido
* GENERATION DATE:  03.07.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.pedido.php
* FOR MYSQL TABLE:  pedido
* FOR MYSQL DB:     stockcontrol
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class pedido
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_produto;   // (normal Attribute)
var $quantidade;   // (normal Attribute)
var $valor;   // (normal Attribute)
var $data;   // (normal Attribute)
var $cliente;   // (normal Attribute)
var $tipo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function pedido()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM pedido WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_produto = $row->idx_produto;

$this->quantidade = $row->quantidade;

$this->valor = $row->valor;

$this->data = $row->data;

$this->cliente = $row->cliente;

$this->tipo = $row->tipo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM pedido WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO pedido ( idx_produto,quantidade,valor,data,cliente,tipo ) VALUES ( '$this->idx_produto','$this->quantidade','$this->valor','$this->data','$this->cliente','$this->tipo' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE pedido SET  idx_produto = '$this->idx_produto',quantidade = '$this->quantidade',valor = '$this->valor',data = '$this->data',cliente = '$this->cliente',tipo = '$this->tipo' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
