
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        aluno
* GENERATION DATE:  10.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/classes/class.aluno.php
* FOR MYSQL TABLE:  aluno
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class aluno
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $nome;   // (normal Attribute)
var $email;   // (normal Attribute)
var $nome_mae;   // (normal Attribute)
var $nome_pai;   // (normal Attribute)
var $responsavel_nome;   // (normal Attribute)
var $responsavel_cpf;   // (normal Attribute)
var $responsavel_rg;   // (normal Attribute)
var $endereco;   // (normal Attribute)
var $plano_saude;   // (normal Attribute)
var $emergencia;   // (normal Attribute)
var $responsavel_emergencia;   // (normal Attribute)
var $carteira;   // (normal Attribute)
var $entregou_carteira;   // (normal Attribute)
var $ativo;   // (normal Attribute)
var $idade;   // (normal Attribute)
var $idx_nivelescolar;   // (normal Attribute)
var $data_nasc;   // (normal Attribute)
var $foto;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function aluno()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM aluno WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->nome = $row->nome;

$this->email = $row->email;

$this->nome_mae = $row->nome_mae;

$this->nome_pai = $row->nome_pai;

$this->responsavel_nome = $row->responsavel_nome;

$this->responsavel_cpf = $row->responsavel_cpf;

$this->responsavel_rg = $row->responsavel_rg;

$this->endereco = $row->endereco;

$this->plano_saude = $row->plano_saude;

$this->emergencia = $row->emergencia;

$this->responsavel_emergencia = $row->responsavel_emergencia;

$this->carteira = $row->carteira;

$this->entregou_carteira = $row->entregou_carteira;

$this->ativo = $row->ativo;

$this->idade = $row->idade;

$this->idx_nivelescolar = $row->idx_nivelescolar;

$this->data_nasc = $row->data_nasc;

$this->foto = $row->foto;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM aluno WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO aluno ( nome,email,nome_mae,nome_pai,responsavel_nome,responsavel_cpf,responsavel_rg,endereco,plano_saude,emergencia,responsavel_emergencia,carteira,entregou_carteira,ativo,idade,idx_nivelescolar,data_nasc,foto ) VALUES ( '$this->nome','$this->email','$this->nome_mae','$this->nome_pai','$this->responsavel_nome','$this->responsavel_cpf','$this->responsavel_rg','$this->endereco','$this->plano_saude','$this->emergencia','$this->responsavel_emergencia','$this->carteira','$this->entregou_carteira','$this->ativo','$this->idade','$this->idx_nivelescolar','$this->data_nasc','$this->foto' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE aluno SET  nome = '$this->nome',email = '$this->email',nome_mae = '$this->nome_mae',nome_pai = '$this->nome_pai',responsavel_nome = '$this->responsavel_nome',responsavel_cpf = '$this->responsavel_cpf',responsavel_rg = '$this->responsavel_rg',endereco = '$this->endereco',plano_saude = '$this->plano_saude',emergencia = '$this->emergencia',responsavel_emergencia = '$this->responsavel_emergencia',carteira = '$this->carteira',entregou_carteira = '$this->entregou_carteira',ativo = '$this->ativo',idade = '$this->idade',idx_nivelescolar = '$this->idx_nivelescolar',data_nasc = '$this->data_nasc',foto = '$this->foto' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
