
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        empresa
* GENERATION DATE:  10.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.empresa.php
* FOR MYSQL TABLE:  empresa
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class empresa
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $razao_social;   // (normal Attribute)
var $responsavel;   // (normal Attribute)
var $cnpj;   // (normal Attribute)
var $endereco;   // (normal Attribute)
var $email;   // (normal Attribute)
var $telefone_comercial;   // (normal Attribute)
var $celular;   // (normal Attribute)
var $logomarca;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function empresa()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM empresa WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->razao_social = $row->razao_social;

$this->responsavel = $row->responsavel;

$this->cnpj = $row->cnpj;

$this->endereco = $row->endereco;

$this->email = $row->email;

$this->telefone_comercial = $row->telefone_comercial;

$this->celular = $row->celular;

$this->logomarca = $row->logomarca;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM empresa WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO empresa ( razao_social,responsavel,cnpj,endereco,email,telefone_comercial,celular,logomarca ) VALUES ( '$this->razao_social','$this->responsavel','$this->cnpj','$this->endereco','$this->email','$this->telefone_comercial','$this->celular','$this->logomarca' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE empresa SET  razao_social = '$this->razao_social',responsavel = '$this->responsavel',cnpj = '$this->cnpj',endereco = '$this->endereco',email = '$this->email',telefone_comercial = '$this->telefone_comercial',celular = '$this->celular',logomarca = '$this->logomarca' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
