
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        horario_servico
* GENERATION DATE:  07.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.horario_servico.php
* FOR MYSQL TABLE:  horario_servico
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class horario_servico
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_servico;   // (normal Attribute)
var $idx_horario;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function horario_servico()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM horario_servico WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_servico = $row->idx_servico;

$this->idx_horario = $row->idx_horario;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM horario_servico WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO horario_servico ( idx_servico,idx_horario ) VALUES ( '$this->idx_servico','$this->idx_horario' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE horario_servico SET  idx_servico = '$this->idx_servico',idx_horario = '$this->idx_horario' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
