
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        aluno
* GENERATION DATE:  02.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.aluno.php
* FOR MYSQL TABLE:  aluno
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class aluno
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $nome;   // (normal Attribute)
var $nome_mae;   // (normal Attribute)
var $nome_pai;   // (normal Attribute)
var $responsavel_nome;   // (normal Attribute)
var $responsavel_cpf;   // (normal Attribute)
var $responsavel_rg;   // (normal Attribute)
var $endereco;   // (normal Attribute)
var $idade;   // (normal Attribute)
var $data_nasc;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function aluno()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM aluno WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->nome = $row->nome;

$this->nome_mae = $row->nome_mae;

$this->nome_pai = $row->nome_pai;

$this->responsavel_nome = $row->responsavel_nome;

$this->responsavel_cpf = $row->responsavel_cpf;

$this->responsavel_rg = $row->responsavel_rg;

$this->endereco = $row->endereco;

$this->idade = $row->idade;

$this->data_nasc = $row->data_nasc;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM aluno WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO aluno ( nome,nome_mae,nome_pai,responsavel_nome,responsavel_cpf,responsavel_rg,endereco,idade,data_nasc ) VALUES ( '$this->nome','$this->nome_mae','$this->nome_pai','$this->responsavel_nome','$this->responsavel_cpf','$this->responsavel_rg','$this->endereco','$this->idade','$this->data_nasc' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE aluno SET  nome = '$this->nome',nome_mae = '$this->nome_mae',nome_pai = '$this->nome_pai',responsavel_nome = '$this->responsavel_nome',responsavel_cpf = '$this->responsavel_cpf',responsavel_rg = '$this->responsavel_rg',endereco = '$this->endereco',idade = '$this->idade',data_nasc = '$this->data_nasc' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
