
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        funcionario_filho
* GENERATION DATE:  11.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.funcionario_filho.php
* FOR MYSQL TABLE:  funcionario_filho
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class funcionario_filho
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_funcionario;   // (normal Attribute)
var $nome;   // (normal Attribute)
var $data_nasc;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function funcionario_filho()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM funcionario_filho WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_funcionario = $row->idx_funcionario;

$this->nome = $row->nome;

$this->data_nasc = $row->data_nasc;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM funcionario_filho WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO funcionario_filho ( idx_funcionario,nome,data_nasc ) VALUES ( '$this->idx_funcionario','$this->nome','$this->data_nasc' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE funcionario_filho SET  idx_funcionario = '$this->idx_funcionario',nome = '$this->nome',data_nasc = '$this->data_nasc' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
