
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        telefone_aluno
* GENERATION DATE:  07.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.telefone_aluno.php
* FOR MYSQL TABLE:  telefone_aluno
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class telefone_aluno
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_aluno;   // (normal Attribute)
var $idx_telefone;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function telefone_aluno()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM telefone_aluno WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_aluno = $row->idx_aluno;

$this->idx_telefone = $row->idx_telefone;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM telefone_aluno WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO telefone_aluno ( idx_aluno,idx_telefone ) VALUES ( '$this->idx_aluno','$this->idx_telefone' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE telefone_aluno SET  idx_aluno = '$this->idx_aluno',idx_telefone = '$this->idx_telefone' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
