
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        usuario
* GENERATION DATE:  02.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.usuario.php
* FOR MYSQL TABLE:  usuario
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class usuario
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $email;   // (normal Attribute)
var $senha;   // (normal Attribute)
var $idx_nivel;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function usuario()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM usuario WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->email = $row->email;

$this->senha = $row->senha;

$this->idx_nivel = $row->idx_nivel;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM usuario WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO usuario ( email,senha,idx_nivel ) VALUES ( '$this->email','$this->senha','$this->idx_nivel' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE usuario SET  email = '$this->email',senha = '$this->senha',idx_nivel = '$this->idx_nivel' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
