
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        atividade_desconto
* GENERATION DATE:  01.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.atividade_desconto.php
* FOR MYSQL TABLE:  atividade_desconto
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class atividade_desconto
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $nome;   // (normal Attribute)
var $idx_atividade;   // (normal Attribute)
var $idx_desconto;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function atividade_desconto()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM atividade_desconto WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->nome = $row->nome;

$this->idx_atividade = $row->idx_atividade;

$this->idx_desconto = $row->idx_desconto;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM atividade_desconto WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO atividade_desconto ( nome,idx_atividade,idx_desconto ) VALUES ( '$this->nome','$this->idx_atividade','$this->idx_desconto' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE atividade_desconto SET  nome = '$this->nome',idx_atividade = '$this->idx_atividade',idx_desconto = '$this->idx_desconto' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
