
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        horario_atividade
* GENERATION DATE:  07.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.horario_atividade.php
* FOR MYSQL TABLE:  horario_atividade
* FOR MYSQL DB:     all4kids
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class horario_atividade
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_atividade;   // (normal Attribute)
var $idx_horario;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function horario_atividade()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM horario_atividade WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_atividade = $row->idx_atividade;

$this->idx_horario = $row->idx_horario;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM horario_atividade WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO horario_atividade ( idx_atividade,idx_horario ) VALUES ( '$this->idx_atividade','$this->idx_horario' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE horario_atividade SET  idx_atividade = '$this->idx_atividade',idx_horario = '$this->idx_horario' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
