
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        equipe_tipo
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.equipe_tipo.php
* FOR MYSQL TABLE:  cad_equipe_tipo
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class equipe_tipo
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $tipo_equipe;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function equipe_tipo()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function gettipo_equipe()
{
return $this->tipo_equipe;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function settipo_equipe($val)
{
$this->tipo_equipe =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_equipe_tipo WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->tipo_equipe = $row->tipo_equipe;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_equipe_tipo WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_equipe_tipo ( tipo_equipe ) VALUES ( '$this->tipo_equipe' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_equipe_tipo SET  tipo_equipe = '$this->tipo_equipe' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
