
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ponto_ref
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.ponto_ref.php
* FOR MYSQL TABLE:  cad_ponto_ref
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class ponto_ref
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $latitude;   // (normal Attribute)
var $longitude;   // (normal Attribute)
var $ponto_nome;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function ponto_ref()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getlatitude()
{
return $this->latitude;
}

function getlongitude()
{
return $this->longitude;
}

function getponto_nome()
{
return $this->ponto_nome;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setlatitude($val)
{
$this->latitude =  $val;
}

function setlongitude($val)
{
$this->longitude =  $val;
}

function setponto_nome($val)
{
$this->ponto_nome =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_ponto_ref WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->latitude = $row->latitude;

$this->longitude = $row->longitude;

$this->ponto_nome = $row->ponto_nome;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_ponto_ref WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_ponto_ref ( latitude,longitude,ponto_nome ) VALUES ( '$this->latitude','$this->longitude','$this->ponto_nome' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_ponto_ref SET  latitude = '$this->latitude',longitude = '$this->longitude',ponto_nome = '$this->ponto_nome' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
