
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        os_despac_sai
* GENERATION DATE:  22.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.os_despac_sai.php
* FOR MYSQL TABLE:  cad_os_despac_sai
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class os_despac_sai
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_os;   // (normal Attribute)
var $idx_despac_sai;   // (normal Attribute)
var $status_os;   // (normal Attribute)
var $data_hora_os;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function os_despac_sai()
{

$this->database = Database::getDb();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getidx_os()
{
return $this->idx_os;
}

function getidx_despac_sai()
{
return $this->idx_despac_sai;
}

function getstatus_os()
{
return $this->status_os;
}

function getdata_hora_os()
{
return $this->data_hora_os;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setidx_os($val)
{
$this->idx_os =  $val;
}

function setidx_despac_sai($val)
{
$this->idx_despac_sai =  $val;
}

function setstatus_os($val)
{
$this->status_os =  $val;
}

function setdata_hora_os($val)
{
$this->data_hora_os =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_os_despac_sai WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_os = $row->idx_os;

$this->idx_despac_sai = $row->idx_despac_sai;

$this->status_os = $row->status_os;

$this->data_hora_os = $row->data_hora_os;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_os_despac_sai WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_os_despac_sai ( idx_os,idx_despac_sai,status_os,data_hora_os ) VALUES ( '$this->idx_os','$this->idx_despac_sai','$this->status_os','$this->data_hora_os' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_os_despac_sai SET  idx_os = '$this->idx_os',idx_despac_sai = '$this->idx_despac_sai',status_os = '$this->status_os',data_hora_os = '$this->data_hora_os' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
