<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        equipe
* GENERATION DATE:  21.05.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\generator/generated_classes/class.equipe.php
* FOR MYSQL TABLE:  cad_equipe
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class equipe
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $cod_equipe;   // (normal Attribute)
var $idx_tipo_equipe;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function equipe()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getcod_equipe()
{
return $this->cod_equipe;
}

function getidx_tipo_equipe()
{
return $this->idx_tipo_equipe;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setcod_equipe($val)
{
$this->cod_equipe =  $val;
}

function setidx_tipo_equipe($val)
{
$this->idx_tipo_equipe =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_equipe WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id = $row->id;

$this->cod_equipe = $row->cod_equipe;

$this->idx_tipo_equipe = $row->idx_tipo_equipe;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_equipe WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_equipe ( cod_equipe,idx_tipo_equipe ) VALUES ( '$this->cod_equipe','$this->idx_tipo_equipe' )";
$result = $this->database->query($sql);
$this->id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_equipe SET  cod_equipe = '$this->cod_equipe',idx_tipo_equipe = '$this->idx_tipo_equipe' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>