
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        propostas
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.propostas.php
* FOR MYSQL TABLE:  propostas
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class propostas
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $titulo;   // (normal Attribute)
var $conteudo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function propostas()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM propostas WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->titulo = $row->titulo;

$this->conteudo = $row->conteudo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM propostas WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO propostas ( titulo,conteudo ) VALUES ( '$this->titulo','$this->conteudo' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE propostas SET  titulo = '$this->titulo',conteudo = '$this->conteudo' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
