
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        downloads
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.downloads.php
* FOR MYSQL TABLE:  downloads
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class downloads
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $arquivo;   // (normal Attribute)
var $descricao;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function downloads()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM downloads WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->arquivo = $row->arquivo;

$this->descricao = $row->descricao;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM downloads WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO downloads ( arquivo,descricao ) VALUES ( '$this->arquivo','$this->descricao' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE downloads SET  arquivo = '$this->arquivo',descricao = '$this->descricao' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
