
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        galeria_interna
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.galeria_interna.php
* FOR MYSQL TABLE:  galeria_interna
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class galeria_interna
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $imagem;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function galeria_interna()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM galeria_interna WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->imagem = $row->imagem;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM galeria_interna WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO galeria_interna ( imagem ) VALUES ( '$this->imagem' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE galeria_interna SET  imagem = '$this->imagem' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
