
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        agenda_conteudo
* GENERATION DATE:  15.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.agenda_conteudo.php
* FOR MYSQL TABLE:  agenda_conteudo
* FOR MYSQL DB:     politicos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class agenda_conteudo
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_agenda;   // (normal Attribute)
var $hora;   // (normal Attribute)
var $conteudo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function agenda_conteudo()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM agenda_conteudo WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_agenda = $row->idx_agenda;

$this->hora = $row->hora;

$this->conteudo = $row->conteudo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM agenda_conteudo WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO agenda_conteudo ( idx_agenda,hora,conteudo ) VALUES ( '$this->idx_agenda','$this->hora','$this->conteudo' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE agenda_conteudo SET  idx_agenda = '$this->idx_agenda',hora = '$this->hora',conteudo = '$this->conteudo' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
