
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        kit_ferramenta
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.kit_ferramenta.php
* FOR MYSQL TABLE:  cad_kit_ferramenta
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class kit_ferramenta
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_ferramenta;   // (normal Attribute)
var $quant_item;   // (normal Attribute)
var $idx_tipo_equipe;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function kit_ferramenta()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_kit_ferramenta WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_ferramenta = $row->idx_ferramenta;

$this->quant_item = $row->quant_item;

$this->idx_tipo_equipe = $row->idx_tipo_equipe;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_kit_ferramenta WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_kit_ferramenta ( idx_ferramenta,quant_item,idx_tipo_equipe ) VALUES ( '$this->idx_ferramenta','$this->quant_item','$this->idx_tipo_equipe' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_kit_ferramenta SET  idx_ferramenta = '$this->idx_ferramenta',quant_item = '$this->quant_item',idx_tipo_equipe = '$this->idx_tipo_equipe' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
