
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        material
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.material.php
* FOR MYSQL TABLE:  cad_material
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class material
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $mat_nome;   // (normal Attribute)
var $idx_unidade;   // (normal Attribute)
var $modelo;   // (normal Attribute)
var $vida_util;   // (normal Attribute)
var $quant_estoque;   // (normal Attribute)
var $idx_fornecedor;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function material()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_material WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->mat_nome = $row->mat_nome;

$this->idx_unidade = $row->idx_unidade;

$this->modelo = $row->modelo;

$this->vida_util = $row->vida_util;

$this->quant_estoque = $row->quant_estoque;

$this->idx_fornecedor = $row->idx_fornecedor;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_material WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_material ( mat_nome,idx_unidade,modelo,vida_util,quant_estoque,idx_fornecedor ) VALUES ( '$this->mat_nome','$this->idx_unidade','$this->modelo','$this->vida_util','$this->quant_estoque','$this->idx_fornecedor' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_material SET  mat_nome = '$this->mat_nome',idx_unidade = '$this->idx_unidade',modelo = '$this->modelo',vida_util = '$this->vida_util',quant_estoque = '$this->quant_estoque',idx_fornecedor = '$this->idx_fornecedor' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
