
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        semaforo
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.semaforo.php
* FOR MYSQL TABLE:  cad_semaforo
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class semaforo
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_uf;   // (normal Attribute)
var $idx_cidade;   // (normal Attribute)
var $idx_bairro;   // (normal Attribute)
var $idx_lograd;   // (normal Attribute)
var $idx_area;   // (normal Attribute)
var $latitude;   // (normal Attribute)
var $longitude;   // (normal Attribute)
var $num_semaforo;   // (normal Attribute)
var $lograd_transver;   // (normal Attribute)
var $modo;   // (normal Attribute)
var $controlador;   // (normal Attribute)
var $operacao;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function semaforo()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_semaforo WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->idx_uf = $row->idx_uf;

$this->idx_cidade = $row->idx_cidade;

$this->idx_bairro = $row->idx_bairro;

$this->idx_lograd = $row->idx_lograd;

$this->idx_area = $row->idx_area;

$this->latitude = $row->latitude;

$this->longitude = $row->longitude;

$this->id = $row->id;

$this->num_semaforo = $row->num_semaforo;

$this->lograd_transver = $row->lograd_transver;

$this->modo = $row->modo;

$this->controlador = $row->controlador;

$this->operacao = $row->operacao;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_semaforo WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_semaforo ( idx_uf,idx_cidade,idx_bairro,idx_lograd,idx_area,latitude,longitude,num_semaforo,lograd_transver,modo,controlador,operacao ) VALUES ( '$this->idx_uf','$this->idx_cidade','$this->idx_bairro','$this->idx_lograd','$this->idx_area','$this->latitude','$this->longitude','$this->num_semaforo','$this->lograd_transver','$this->modo','$this->controlador','$this->operacao' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_semaforo SET  idx_uf = '$this->idx_uf',idx_cidade = '$this->idx_cidade',idx_bairro = '$this->idx_bairro',idx_lograd = '$this->idx_lograd',idx_area = '$this->idx_area',latitude = '$this->latitude',longitude = '$this->longitude',num_semaforo = '$this->num_semaforo',lograd_transver = '$this->lograd_transver',modo = '$this->modo',controlador = '$this->controlador',operacao = '$this->operacao' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
