
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        veiculo
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.veiculo.php
* FOR MYSQL TABLE:  cad_veiculo
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class veiculo
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $placa;   // (normal Attribute)
var $ano;   // (normal Attribute)
var $idx_modelo;   // (normal Attribute)
var $idx_tipo;   // (normal Attribute)
var $imei_gps;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function veiculo()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_veiculo WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->placa = $row->placa;

$this->ano = $row->ano;

$this->idx_modelo = $row->idx_modelo;

$this->idx_tipo = $row->idx_tipo;

$this->imei_gps = $row->imei_gps;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_veiculo WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_veiculo ( placa,ano,idx_modelo,idx_tipo,imei_gps ) VALUES ( '$this->placa','$this->ano','$this->idx_modelo','$this->idx_tipo','$this->imei_gps' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_veiculo SET  placa = '$this->placa',ano = '$this->ano',idx_modelo = '$this->idx_modelo',idx_tipo = '$this->idx_tipo',imei_gps = '$this->imei_gps' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
