
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        usuarios
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.usuarios.php
* FOR MYSQL TABLE:  cad_usuarios
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class usuarios
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $idx_niv_acesso;   // (normal Attribute)
var $senha;   // (normal Attribute)
var $contrat_acesso;   // (normal Attribute)
var $usuario;   // (normal Attribute)
var $idx_empresa_usua;   // (normal Attribute)
var $login_nome;   // (normal Attribute)
var $nivelacesso;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function usuarios()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_usuarios WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->idx_niv_acesso = $row->idx_niv_acesso;

$this->senha = $row->senha;

$this->contrat_acesso = $row->contrat_acesso;

$this->usuario = $row->usuario;

$this->idx_empresa_usua = $row->idx_empresa_usua;

$this->login_nome = $row->login_nome;

$this->nivelacesso = $row->nivelacesso;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_usuarios WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_usuarios ( idx_niv_acesso,senha,contrat_acesso,usuario,idx_empresa_usua,login_nome,nivelacesso ) VALUES ( '$this->idx_niv_acesso','$this->senha','$this->contrat_acesso','$this->usuario','$this->idx_empresa_usua','$this->login_nome','$this->nivelacesso' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_usuarios SET  idx_niv_acesso = '$this->idx_niv_acesso',senha = '$this->senha',contrat_acesso = '$this->contrat_acesso',usuario = '$this->usuario',idx_empresa_usua = '$this->idx_empresa_usua',login_nome = '$this->login_nome',nivelacesso = '$this->nivelacesso' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
