
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ocorrencia
* GENERATION DATE:  17.06.2014
* CLASS FILE:       C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\generator/classes/class.ocorrencia.php
* FOR MYSQL TABLE:  cad_ocorrencia
* FOR MYSQL DB:     geoss
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class ocorrencia
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $tipo_ocorrenc;   // (normal Attribute)
var $idx_ocorrenc_prior;   // (normal Attribute)
var $idx_tipo_veic;   // (normal Attribute)
var $prazo_atend;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function ocorrencia()
{

$this->database = Database::getDb();

}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cad_ocorrencia WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = $result->fetch_object();


$this->id = $row->id;

$this->tipo_ocorrenc = $row->tipo_ocorrenc;

$this->idx_ocorrenc_prior = $row->idx_ocorrenc_prior;

$this->idx_tipo_veic = $row->idx_tipo_veic;

$this->prazo_atend = $row->prazo_atend;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cad_ocorrencia WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO cad_ocorrencia ( tipo_ocorrenc,idx_ocorrenc_prior,idx_tipo_veic,prazo_atend ) VALUES ( '$this->tipo_ocorrenc','$this->idx_ocorrenc_prior','$this->idx_tipo_veic','$this->prazo_atend' )";
$result = $this->database->query($sql);


}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cad_ocorrencia SET  tipo_ocorrenc = '$this->tipo_ocorrenc',idx_ocorrenc_prior = '$this->idx_ocorrenc_prior',idx_tipo_veic = '$this->idx_tipo_veic',prazo_atend = '$this->prazo_atend' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
